---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.71.199
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: odv
    ansible_ssh_private_key_file: "/home/{{ ansible_user }}/.ssh/netology"
    ansible_python_interpreter: /usr/bin/python3