apiVersion: v1
kind: Service
metadata:
  name: service-nodeport1

spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      nodePort: 30080
      
  selector:
    app: app1

  type: NodePort