services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    #environment:
      # increases the log level from info to debug
      # - GF_LOG_LEVEL=debug
    ports:
      - '3000:3000'
    volumes:
      - './grafana/storage:/var/lib/grafana'
      - './grafana/alerting:/etc/grafana/provisioning/alerting'
    depends_on:
      - prometheus  

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: Cgbybyu
      GF_USERS_ALLOW_SIGN_UP: false    
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus/data:/prometheus'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    depends_on:
      - prometheus

volumes:
  grafana_storage: {}