global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance_name: "prometheus"

  # -- API GATEWAY metrics endpoinds --

  - job_name: "uploader"
    static_configs:
      - targets: ['uploader:3000']  
    metrics_path: "/metrics" 

  - job_name: "security"
    static_configs:
      - targets: ["security:3000"]
    metrics_path: "/metrics"

  - job_name: "storage"
    static_configs:
      - targets: ["storage:9000"]
    metrics_path: "/minio/v2/metrics/cluster"      