---
clickhouse:
  hosts:
    clickhouse-1:
      ansible_host: 158.160.97.222
      ansible_user: odv
      ansible_ssh_private_key_file: /home/odv/.ssh/netology
lighthouse:
  hosts:
    lighthouse-1:
      ansible_host: 158.160.98.242
      ansible_user: odv
      ansible_ssh_private_key_file: /home/odv/.ssh/netology
vector:
  hosts:
    vector-1:
      ansible_host: 46.21.245.167
      ansible_user: odv
      ansible_ssh_private_key_file: /home/odv/.ssh/netology
