apiVersion: 1
groups:
  - orgId: 1
    name: main
    folder: main
    interval: 30s
    rules: []
groups:
  - orgId: 1
    name: dummy-labels
    folder: dummy
    interval: 30s
    rules:
      - uid: dummy-cpu
        title: Dummy CPU Alert
        condition: C
        labels:
          severity: critical
          type: cpu
        data:
          - refId: A
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: prometheus
            model:
              expr: vector(0)
              instant: true
              refId: A
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [C]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              refId: C
              type: threshold
        isPaused: true

      - uid: dummy-disk
        title: Dummy Disk Alert
        condition: C
        labels:
          severity: warning
          type: disk
        data:
          - refId: A
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: prometheus
            model:
              expr: vector(0)
              instant: true
              refId: A
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [C]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              refId: C
              type: threshold
        isPaused: true

      - uid: dummy-mem
        title: Dummy Memory Alert
        condition: C
        labels:
          severity: info
          type: mem
        data:
          - refId: A
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: prometheus
            model:
              expr: vector(0)
              instant: true
              refId: A
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [C]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              refId: C
              type: threshold
        isPaused: true

