{
 "title": "Host CPU LA",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "MAIN HOST DISK FREE SIZE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|cifs\", instance_name=\"main_host\"} ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "MAIN HOST FREE MEM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance_name=\"main_host\"}",
     "legendFormat": "Free memory"
    }
   ]
  },
  {
   "title": "MAIN HOST CPU UTILIZATION %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance_name) (\n    rate(node_cpu_seconds_total{instance_name=\"main_host\", mode=\"idle\"}[2m])\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAIN HOST CPU LA",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{__name__=~\"node_load(1|5|15)\", instance=\"node-exporter:9100\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}