global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance_name: "prometheus"
  - job_name: "host_node"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          instance_name: "main_host"